import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Dashboard from '@/components/Dashboard'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang="en">
      <body className={cn(inter.className, "h-screen")}>
        <Dashboard>
          {children}
        </Dashboard></body>
    </html>
  )
}

export default RootLayout
